version: '3'
services:
  node:
    build:
      context: node
    container_name: node
    restart: always
    tty: true
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - db
    networks:
      - node-nginx
  nginx:
    build:
      context: ngnix
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - node-nginx
    depends_on:
      - node
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
    networks:
      - node-nginx

networks:
  node-nginx:
    driver: bridge
